import boto3  
from botocore.config import Config
import awswrangler as wr

# Configurar la sesión de AWS
my_config = Config(
    region_name = 'us-east-1'
)

session = boto3.Session(profile_name='arquitectura',region_name="us-east-1")

# Crear la tabla de variables de buro
query_1 = '''
     CREATE EXTERNAL TABLE IF NOT EXISTS `analisis_buro`.`variables_buro` (
     `MES` INT,
     `CLIENTEID` INT,
     `SH01_Hit_Indicator` INT,
     `Score_1` DOUBLE,
     `Score_1_Derogatory_Alert` STRING,
     `Number_of_trades` DOUBLE,
     `Number_of_trades_opened_in_past_12_months` DOUBLE,
     `Number_of_trades_opened_in_past_24_months` DOUBLE,
     `Months_since_oldest_account_opened` DOUBLE,
     `Months_since_most_recent_account_opened` DOUBLE,
     `Number_of_trades_with_current_balance_balance_greater_than_0` DOUBLE,
     `Number_of_bankcard_accounts` DOUBLE,
     `Number_of_currently_active_bankcard_accounts` DOUBLE,
     `Number_of_bankcard_accounts_opened_in_past_12_months` DOUBLE,
     `Number_of_bankcard_accounts_opened_in_past_24_months` DOUBLE,
     `Months_since_oldest_bankcard_account_opened` DOUBLE,
     `Months_since_most_recent_bankcard_account_opened` DOUBLE,
     `Number_of_bankcard_accounts_with_current_balance_balance_greater_than_0` DOUBLE,
     `Number_of_bank_installment_accounts` DOUBLE,
     `Number_of_bank_installment_accounts_opened_in_past_12_months` DOUBLE,
     `Number_of_bank_installment_accounts_opened_in_past_24_months` DOUBLE,
     `Months_since_oldest_bank_installment_account_opened` DOUBLE,
     `Number_of_finance_installment_trades` DOUBLE,
     `Number_of_finance_installment_trades_opened_in_past_12_months` DOUBLE,
     `Number_of_finance_installment_trades_opened_in_past_24_months` DOUBLE,
     `Months_since_most_recent_activity` DOUBLE,
     `Months_on_file` DOUBLE,
     `Number_of_installment_accounts` DOUBLE,
     `Number_of_currently_active_installment_trades` DOUBLE,
     `Number_of_installment_accounts_opened_in_past_12_months` DOUBLE,
     `Number_of_installment_accounts_opened_in_past_24_months` DOUBLE,
     `Months_since_oldest_installment_account_opened` DOUBLE,
     `Months_since_most_recent_installment_accounts_opened` DOUBLE,
     `Number_of_installment_trades_with_balance_balance_greater_than_0` DOUBLE,
     `Number_of_mortgage_accounts` DOUBLE,
     `Number_of_currently_active_mortgage_accounts` DOUBLE,
     `Number_of_mortgage_accounts_opened_in_past_12_months` DOUBLE,
     `Number_of_mortgage_accounts_opened_in_past_24_months` DOUBLE,
     `Months_since_oldest_mortgage_account_opened` DOUBLE,
     `Months_since_most_recent_mortgage_account_opened` DOUBLE,
     `Number_of_mortgage_accounts_with_current_balance_greater_than_0` DOUBLE,
     `Number_of_personal_finance_accounts` DOUBLE,
     `Number_of_currently_active_personal_finance_accounts` DOUBLE,
     `Number_of_personal_finance_accounts_opened_in_past_12_months` DOUBLE,
     `Number_of_personal_finance_accounts_opened_in_past_24_months` DOUBLE,
     `Months_since_oldest_personal_finance_account_opened` DOUBLE,
     `Months_since_most_recent_personal_finance_account_opened` DOUBLE,
     `Number_of_personal_finance_trades_with_balance_balance_greater_than_0` DOUBLE,
     `Number_of_revolving_accounts` DOUBLE,
     `Number_of_currently_active_revolving_trades` DOUBLE,
     `Number_of_revolving_trades_opened_in_past_12_months` DOUBLE,
     `Number_of_revolving_trades_opened_in_past_24_months` DOUBLE,
     `Months_since_oldest_revolving_account_opened` DOUBLE,
     `Months_since_most_recent_revolving_account_opened` DOUBLE,
     `Number_of_revolving_trades_with_balance_balance_greater_than_0` DOUBLE,
     `Number_of_retail_trades` DOUBLE,
     `Number_of_currently_active_retail_trades` DOUBLE,
     `Number_of_retail_trades_opened_in_past_12_months` DOUBLE,
     `Number_of_retail_trades_opened_in_past_24_months` DOUBLE,
     `Months_since_oldest_retail_account_opened` DOUBLE,
     `Months_since_most_recent_retail_account_opened` DOUBLE,
     `Number_of_retail_trades_with_current_balance_balance_greater_than_0` DOUBLE,
     `Number_of_open_trades` DOUBLE,
     `Number_of_open_revolving_trades` DOUBLE,
     `Number_of_accounts_opened_since_the_last_maximum_delinquency_of_60_day_past_due` DOUBLE,
     `Number_of_accounts_opened_since_the_last_charge_off` DOUBLE,
     `Number_of_accounts_with_a_maximum_delinquency_of_60_days_past_due_since_opening_a_new_account_within_the_last_12_months` DOUBLE,
     `Number_of_accounts_with_a_maximum_delinquency_of_90_days_plus_past_due_since_opening_a_new_account_within_the_last_12_months` DOUBLE,
     `Number_of_accounts_Charged_Off_since_opening_a_new_account_within_the_last_12_months` DOUBLE,
     `Number_of_satisfactory_trades` DOUBLE,
     `Months_since_most_recent_delinquency` DOUBLE,
     `Number_of_satisfactory_bankcard_accounts` DOUBLE,
     `Months_since_most_recent_bankcard_delinquency` DOUBLE,
     `Number_of_satisfactory_bank_installment_accounts` DOUBLE,
     `Number_of_charge_offs_within_12_months_CHGOFF12` DOUBLE,
     `Highest_collection_amount_owed_in_12_months_COLAMT12` DOUBLE,
     `Number_of_collection_inquiries_COLINQ` DOUBLE,
     `Number_of_collections_in_12_months_COLLEC12` DOUBLE,
     `Number_of_collections_in_12_months_excluding_medical_collections_COLXMD12` DOUBLE,
     `Number_of_satisfactory_finance_installment_trades` DOUBLE,
     `Number_of_30_day_ratings` DOUBLE,
     `Number_of_60_day_ratings` DOUBLE,
     `Number_of_90_day_ratings` DOUBLE,
     `Number_of_120_day_ratings` DOUBLE,
     `Number_of_30_and_60_day_ratings` DOUBLE,
     `Number_of_30_day_or_worse_ratings` DOUBLE,
     `Number_of_60_day_or_worse_ratings` DOUBLE,
     `Number_of_90_day_or_worse_ratings` DOUBLE,
     `Number_of_trades_with_maximum_delinquency_02_in_last_3_months` DOUBLE,
     `Number_of_trades_with_maximum_delinquency_02_in_last_6_months` DOUBLE,
     `Number_of_trades_with_maximum_delinquency_02_in_last_12_months` DOUBLE,
     `Number_of_trades_with_maximum_delinquency_02_in_last_24_months` DOUBLE,
     `Number_of_trades_with_maximum_delinquency_03_in_last_3_months` DOUBLE,
     `Number_of_trades_with_maximum_delinquency_03_in_last_6_months` DOUBLE,
     `Number_of_trades_with_maximum_delinquency_03_in_last_12_months` DOUBLE,
     `Number_of_trades_with_maximum_delinquency_03_in_last_24_months` DOUBLE,
     `Number_of_trades_with_maximum_delinquency_04_in_last_3_months` DOUBLE,
     `Number_of_trades_with_maximum_delinquency_04_in_last_6_months` DOUBLE,
     `Number_of_trades_with_maximum_delinquency_04_in_last_12_months` DOUBLE,
     `Number_of_trades_with_maximum_delinquency_04_in_last_24_months` DOUBLE,
     `Number_of_trades_ever_30_or_more_days_past_due` DOUBLE,
     `Number_of_trades_ever_60_or_more_days_past_due` DOUBLE,
     `Number_of_trades_ever_90_or_more_days_past_due` DOUBLE,
     `Number_of_trades_ever_120_or_more_days_past_due` DOUBLE,
     `Percent_of_trades_delinquent` DOUBLE,
     `Number_of_trades_30_or_more_days_past_due_in_last_3_months` DOUBLE,
     `Number_of_trades_30_or_more_days_past_due_in_last_6_months` DOUBLE,
     `Number_of_trades_30_or_more_days_past_due_in_last_12_months` DOUBLE,
     `Number_of_trades_30_or_more_days_past_due_in_last_24_months` DOUBLE,
     `Number_of_trades_60_or_more_days_past_due_in_last_3_months` DOUBLE,
     `Number_of_trades_60_or_more_days_past_due_in_last_6_months` DOUBLE,
     `Number_of_trades_60_or_more_days_past_due_in_last_12_months` DOUBLE,
     `Number_of_trades_60_or_more_days_past_due_in_last_24_months` DOUBLE,
     `Number_of_trades_90_or_more_days_past_due_in_last_3_months` DOUBLE,
     `Number_of_trades_90_or_more_days_past_due_in_last_6_months` DOUBLE,
     `Number_of_trades_90_or_more_days_past_due_in_last_12_months` DOUBLE,
     `Number_of_trades_90_or_more_days_past_due_in_last_24_months` DOUBLE,
     `Number_of_trades_currently_past_due_updated_in_past_2_months` DOUBLE,
     `Number_of_trades_currently_30_days_past_due_updated_in_past_2_months` DOUBLE,
     `Number_of_trades_currently_60_days_past_due_updated_in_past_2_months` DOUBLE,
     `Number_of_trades_currently_90_days_past_due_updated_in_past_2_months` DOUBLE,
     `Number_of_trades_currently_120_days_past_due_updated_in_past_2_months` DOUBLE,
     `Total_amount_now_past_due` DOUBLE,
     `Number_of_derogatory_public_records` DOUBLE,
     `Number_of_public_record_bankruptcies` DOUBLE,
     `Months_since_most_recent_derogatory_public_record` DOUBLE,
     `Number_of_satisfactory_mortgage_accounts` DOUBLE,
     `Months_since_most_recent_mortgage_account_delinquency` DOUBLE,
     `Number_of_satisfactory_personal_finance_accounts` DOUBLE,
     `Months_since_most_recent_personal_finance_delinquency` DOUBLE,
     `Number_of_satisfactory_revolving_accounts` DOUBLE,
     `Months_since_most_recent_revolving_delinquency` DOUBLE,
     `Number_of_satisfactory_retail_trades` DOUBLE,
     `Months_since_most_recent_retail_delinquency` DOUBLE,
     `Number_of_public_record_and_account_line_derogatory_items_greater_than_100` DOUBLE,
     `Months_since_most_recent_60_day_or_worse_rating` DOUBLE,
     `Months_since_most_recent_90_day_or_worse_rating` DOUBLE,
     `Total_public_record_amounts` DOUBLE,
     `Total_collection_amounts_ever_owed` DOUBLE,
     `Number_of_tax_liens` DOUBLE,
     `Total_high_credit_credit_limit` DOUBLE,
     `Total_bankcard_high_credit_credit_limit` DOUBLE,
     `Total_installment_high_credit_credit_limit` DOUBLE,
     `Total_mortgage_high_credit_credit_limit` DOUBLE,
     `Total_personal_finance_high_credit_credit_limit` DOUBLE,
     `Total_revolving_high_credit_credit_limit` DOUBLE,
     `Total_retail_high_credit_credit_limit` DOUBLE,
     `Highest_retail_high_credit_credit_limit` DOUBLE,
     `Total_current_balance_of_all_trades` DOUBLE,
     `Average_current_balance_of_all_trades` DOUBLE,
     `Total_current_balance_of_all_trades_excluding_mortgage` DOUBLE,
     `Maximum_balance_owed_on_all_bankcard_accounts` DOUBLE,
     `Total_balance_of_all_bankcard_accounts` DOUBLE,
     `Average_current_balance_of_all_bankcard_accounts` DOUBLE,
     `Maximum_balance_owed_on_all_finance_installment_trades` DOUBLE,
     `Total_current_balance_of_all_installment_accounts` DOUBLE,
     `Average_balance_of_all_installment_trades` DOUBLE,
     `Maximum_current_balance_owed_on_all_mortgage_accounts` DOUBLE,
     `Total_current_balance_of_all_mortgage_accounts` DOUBLE,
     `Average_current_balance_of_mortgage_accounts` DOUBLE,
     `Maximum_balance_owed_on_all_personal_finance_trades` DOUBLE,
     `Total_current_balance_of_all_personal_finance_accounts` DOUBLE,
     `Average_balance_of_all_personal_finance_trades` DOUBLE,
     `Maximum_current_balance_owed_on_all_revolving_accounts` DOUBLE,
     `Total_current_balance_of_all_revolving_accounts` DOUBLE,
     `Average_current_balance_of_all_revolving_accounts` DOUBLE,
     `Maximum_balance_owed_on_all_retail_trades` DOUBLE,
     `Total_current_balance_of_all_retail_trades` DOUBLE,
     `Average_current_balance_of_all_retail_trades` DOUBLE,
     `Number_of_non_installment_trades_50_of_limit` DOUBLE,
     `Percent_of_active_trades_with_current_balance_balance_greater_than_0` DOUBLE,
     `Ratio_of_total_current_balance_to_high_credit_credit_limit_for_all_trades` DOUBLE,
     `Percentage_of_all_bankcard_accounts_50_of_limit` DOUBLE,
     `Percentage_of_all_bankcard_accounts_75_of_limit` DOUBLE,
     `Ratio_of_total_current_balance_to_high_credit_credit_limit_for_all_bankcard_accounts` DOUBLE,
     `Total_open_to_buy_on_revolving_bankcards_includes_retail_and_gascards` DOUBLE,
     `Ratio_of_total_balance_to_high_credit_credit_limit_for_all_bank_revolving_accounts` DOUBLE,
     `Ratio_of_total_current_balance_to_high_credit_credit_limit_for_all_installment_accounts` DOUBLE,
     `Ratio_of_current_balance_to_high_credit_credit_limit_on_mortgage_accounts` DOUBLE,
     `Ratio_of_total_current_balance_to_high_credit_credit_limit_for_all_personal_finance_accounts` DOUBLE,
     `Ratio_of_total_current_balance_to_high_credit_credit_limit_for_all_revolving_accounts` DOUBLE,
     `Ratio_of_total_current_balance_to_high_credit_credit_limit_for_all_retail_trades` DOUBLE,
     `Number_of_inquiries` DOUBLE,
     `Number_or_inquiries_in_last_6_months` DOUBLE,
     `Months_since_most_recent_inquiry` DOUBLE,
     `Score_1_Indicator_Flag` DOUBLE,
     `Deceased_Flag` STRING,
     `Frozen_Flag_Indicator` STRING,
     `Fact_Act_Address_Type` STRING,
     `FECHA_CONSULTA` DATE,
     `FECHA_INFORMACION` DATE,
     `MES_INFORMACION` INT
     ) COMMENT "Variables de buro de credito completas"
     ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
     WITH SERDEPROPERTIES ('field.delim' = ',')
     STORED AS INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
     OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
     LOCATION 's3://itam-analytics-ogf/analisis_variables_buro/db_buro/'
     TBLPROPERTIES ('classification' = 'csv', "skip.header.line.count"="1");
'''

# Ejecutar la consulta
wr.athena.read_sql_query(
    query_1, 
    database="analisis_buro", 
    ctas_approach=False, 
    boto3_session=session
)

# Crear la tabla de performance
query_2 = '''
     CREATE EXTERNAL TABLE IF NOT EXISTS `analisis_buro`.`performance` (
     `CLIENTEID` INT,
     `DESEMPENIO` INT,
     `MIS` DATE,
     `OVER30` INT,
     `DAYS_OFF` INT
     ) COMMENT "Performance de los clientes en tabla de buro."
     ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
     WITH SERDEPROPERTIES ('field.delim' = ',')
     STORED AS INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
     OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
     LOCATION 's3://itam-analytics-ogf/analisis_variables_buro/db_performance/'
     TBLPROPERTIES ('classification' = 'csv', "skip.header.line.count"="1");
'''

# Ejecutar la consulta
wr.athena.read_sql_query(
    query_2, 
    database="analisis_buro", 
    ctas_approach=False, 
    boto3_session=session
)